export const LOAD_ACTIVITY_INFO = 'LOAD_ACTIVITY_INFO'
export const LOAD_ACTIVITY_INFO_BEGIN = 'LOAD_ACTIVITY_INFO_BEGIN'
export const LOAD_ACTIVITY_INFO_END = 'LOAD_ACTIVITY_INFO_END'
export const LOAD_ACTIVITY_INFO_ERROR = 'LOAD_ACTIVITY_INFO_ERROR'
export const UPDATE_ACTIVITY_JOINTIMES = 'UPDATE_ACTIVITY_JOINTIMES'
export const GET_EXTENSION_CODE = 'GET_EXTENSION_CODE'

export const LAUNCH_LOTTERY = 'LAUNCH_LOTTERY'
export const LAUNCH_LOTTERY_BEGIN = 'LAUNCH_LOTTERY_BEGIN'
export const LAUNCH_LOTTERY_END = 'LAUNCH_LOTTERY_END'
export const LAUNCH_LOTTERY_ERROR = 'LAUNCH_LOTTERY_ERROR'

export const LOAD_LUCKY_LIST = 'LOAD_LUCKY_LIST'
export const LOAD_LUCKY_LIST_BEGIN = 'LOAD_LUCKY_LIST_BEGIN'
export const LOAD_LUCKY_LIST_END = 'LOAD_LUCKY_LIST_END'
export const LOAD_LUCKY_LIST_ERROR = 'LOAD_LUCKY_LIST_ERROR'

export const WECHAT_CONFIG = 'WECHAT_SIGN'
export const WECHAT_CONFIG_BEGIN = 'WECHAT_CONFIG_BEGIN'
export const WECHAT_CONFIG_END = 'WECHAT_CONFIG_END'
export const WECHAT_CONFIG_ERROR = 'WECHAT_CONFIG_ERROR'

export const RECORD_SHARE = 'RECORD_SHARE'
export const RECORD_SHARE_BEGIN = 'RECORD_SHARE_BEGIN'
export const RECORD_SHARE_END = 'RECORD_SHARE_END'
export const RECORD_SHARE_ERROR = 'RECORD_SHARE_ERROR'


export const UPDATE_GLOBAL_LOADING = 'UPDATE_GLOBAL_LOADING'

export default {
  WECHAT_CONFIG,
  WECHAT_CONFIG_BEGIN,
  WECHAT_CONFIG_END,
  WECHAT_CONFIG_ERROR,
  LOAD_LUCKY_LIST,
  LOAD_LUCKY_LIST_BEGIN,
  LOAD_LUCKY_LIST_END,
  LOAD_LUCKY_LIST_ERROR,
  LAUNCH_LOTTERY,
  LAUNCH_LOTTERY_BEGIN,
  LAUNCH_LOTTERY_END,
  LAUNCH_LOTTERY_ERROR,
  LOAD_ACTIVITY_INFO,
  LOAD_ACTIVITY_INFO_BEGIN,
  LOAD_ACTIVITY_INFO_END,
  LOAD_ACTIVITY_INFO_ERROR,
  GET_EXTENSION_CODE,
  UPDATE_ACTIVITY_JOINTIMES,
  UPDATE_GLOBAL_LOADING,
  RECORD_SHARE,
  RECORD_SHARE_BEGIN,
  RECORD_SHARE_END,
  RECORD_SHARE_ERROR,
}
