export const LOAD_ACTIVITY_INFO = 'LOAD_ACTIVITY_INFO'
export const LOAD_ACTIVITY_INFO_BEGIN = 'LOAD_ACTIVITY_INFO_BEGIN'
export const LOAD_ACTIVITY_INFO_END = 'LOAD_ACTIVITY_INFO_END'
export const LOAD_ACTIVITY_INFO_ERROR = 'LOAD_ACTIVITY_INFO_ERROR'
export const UPDATE_ACTIVITY_JOINTIMES = 'UPDATE_ACTIVITY_JOINTIMES'

export const LAUNCH_LOTTERY = 'LAUNCH_LOTTERY'
export const LAUNCH_LOTTERY_BEGIN = 'LAUNCH_LOTTERY_BEGIN'
export const LAUNCH_LOTTERY_END = 'LAUNCH_LOTTERY_END'
export const LAUNCH_LOTTERY_ERROR = 'LAUNCH_LOTTERY_ERROR'

export const LOAD_LUCKY_LIST = 'LOAD_LUCKY_LIST'
export const LOAD_LUCKY_LIST_BEGIN = 'LOAD_LUCKY_LIST_BEGIN'
export const LOAD_LUCKY_LIST_END = 'LOAD_LUCKY_LIST_END'
export const LOAD_LUCKY_LIST_ERROR = 'LOAD_LUCKY_LIST_ERROR'


export const UPDATE_GLOBAL_LOADING = 'UPDATE_GLOBAL_LOADING'

export default {
  LOAD_LUCKY_LIST,
  LOAD_LUCKY_LIST_BEGIN,
  LOAD_LUCKY_LIST_END,
  LOAD_LUCKY_LIST_ERROR,
  LAUNCH_LOTTERY,
  LAUNCH_LOTTERY_BEGIN,
  LAUNCH_LOTTERY_END,
  LAUNCH_LOTTERY_ERROR,
  LOAD_ACTIVITY_INFO,
  LOAD_ACTIVITY_INFO_BEGIN,
  LOAD_ACTIVITY_INFO_END,
  LOAD_ACTIVITY_INFO_ERROR,
  UPDATE_ACTIVITY_JOINTIMES,
  UPDATE_GLOBAL_LOADING,
}
