export const RECIEVE_TOP_PRODUCTS = 'RECIEVE_TOP_PRODUCTS'
export const RECIEVE_SPECIAL_PRODUCTS = 'RECIEVE_SPECIAL_PRODUCTS'
export const RECIEVE_ADVERTISE = 'RECIEVE_ADVERTISE'
export const PENDING_REQUEST_COUNT_INCRUMENT = 'PENDING_REQUEST_COUNT_INCRUMENT'
export const PENDING_REQUEST_COUNT_DECRUMENT = 'PENDING_REQUEST_COUNT_DECRUMENT'
export const NETWORK_ERROR_HANDLE = 'NETWORK_ERROR_HANDLE'
export const NETWORK_RESOLVE_HANDLE = 'NETWORK_RESOLVE_HANDLE'
export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG'
export const SET_ERROR_MSG = 'SET_ERROR_MSG'

export default {
  RECIEVE_TOP_PRODUCTS,
  RECIEVE_SPECIAL_PRODUCTS,
  RECIEVE_ADVERTISE,
  PENDING_REQUEST_COUNT_INCRUMENT,
  PENDING_REQUEST_COUNT_DECRUMENT,
  NETWORK_ERROR_HANDLE,
  NETWORK_RESOLVE_HANDLE,
}
